import re

def normalize(text):
    # print(text_list)
    text = text.replace('&lt;', '<')
    text = text.replace('&gt;', '>')
    text = text.replace('&amp;', '&')
    text = text.replace('&quot;', '"')
    text = text.replace('&#39;', "'").replace('&apos;', "'")
    text = text.replace('&#150;', '–')
    text = text.replace('&nbsp;', ' ')
    text = text.replace('&#160;', ' ')
    text = text.replace('&#039;', "'")
    text = text.replace('&#34;', '"')
    text = text.replace('&reg;', '®')
    text = text.replace('&rsquo;', '’')
    text = text.replace('&#8226;', '•')
    text = text.replace('&ndash;', '–')
    text = text.replace('&#x27;', "'")
    text = text.replace('&#40;', '(')
    text = text.replace('&#41;', ')')
    text = text.replace('&#47;', '/')
    text = text.replace('&#43;', '+')
    text = text.replace('&#035;', '#')
    text = text.replace('&#38;', '&')
    text = text.replace('&eacute;', 'é')
    text = text.replace('&frac12;', '½')
    text = re.sub(r"\s+", "", text)
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    return text.strip()

